### PR TITLE
Upgrade to elm 0.19

### PR DESCRIPTION
**Pull request by azuken**

### CODE REVIEW

**Comment by athanclark** [comment]
@azuken I've basically abandoned this project. Would you like to take ownership of it?

**Comment by azuken** [comment]
@athanclark If you want, it does not bother me

**Comment by azuken** [comment]
I've never added a package on elm packages, I must create a new one ?

**Comment by athanclark** [comment]
@azuken, I don't think you need to make a new registry for it, but I haven't used elm in years. Here, I'll add you as a contributor, then we can figure out how to re-host the newest version. Let's hope it just follows tagged versions like bower.

**Comment by azuken** [comment]
@athanclark Ok, I will take a look later, thanks.

**Comment by azuken** [comment]
@athanclark I've juste merged new version to master, how can I push it to elm packages now ?

Edit : I've pushed a new version 4.0.0 with `elm publish`, I'm waiting now for website refresh

**Pull request merged**
